name: Build MSound
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode Project
        run: xcodegen generate

      - name: Build and Archive
        run: |
          xcodebuild archive -project MSound.xcodeproj \
                             -scheme MSound \
                             -archivePath MSound.xcarchive \
                             -sdk iphoneos \
                             -configuration Release \
                             CODE_SIGNING_ALLOWED=NO \
                             CODE_SIGNING_REQUIRED=NO \
                             ENTITLEMENTS_REQUIRED=NO

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: MSound-Archive
          path: MSound.xcarchive
          
